### ISSUE TITLE
UsingS2EGet.rst confusing and failed in using s2eget

### ISSUE THREAD

**Issue by Qining** [dslab-epfl/s2e#80]
I found the tutorial is very unclear here, as a newbie of s2e I found some part are missing in the tutorial and some subtle but important parts are not emphasized.

1. I can find nowhere explicitly explained what is 's2e mode' and what is 'non s2e mode', I guess that means  'i386_s2e_softmmu/' vs 'i386_softmmu'. But I can never be sure, as I encountered many problem during following the tutorial.

2. I think you should mention when 'kvm' can be enabled, and when it cannot. Currently it is a very subtle decision that a new user without any background of S2E feel very confusing and causes crashes so many times.

3. I think you should mention that you have enabled snapshot when using '*.s2e'. Just showing '*.s2e' is equivalent to '*.raw' only does one thing: misleading new users use *.raw instead of *.s2e as their image, and we don't know why have a new suffix at all (no one explain).

4. OK, a real problem I have now. I tried to use s2eget as said in the UsingS2EGet.rst. But I failed. There are two scenarios: a. If I start qemu without -s2e-config-file flag (like said in UsingS2EGet.rst), I will get a assertion fail:
```
s2e/Plugins/CorePlugin.cpp:113: void s2e_tcg_custom_instruction_handler(uint64_t): Assertion `!g_s2e->getCorePlugin()->onCustomInstruction.empty() && "You must activate a plugin that uses custom instructions."' failed.
```

I guess this is because some plugin in not activated, so I find the flag: -s2e-config-file. And the only file looks like a 'config file' is the one we just created 'config.lua'. So I tried as follow:

Start with -s2e-config-file ./config.lua, then I get hang in the VM (just like the hang in no s2e mode qemu).

And, In the tutorial, we cannot find how to refer to the config file: config.lua. 

Could anyone help me out from this trouble? 

Thanks,

**Comment by vitalych** [comment]
Thanks for the input. 
- KVM can (and should) be used to install the image. Then DBT mode (i386_softmmu) can be used to take a snapshot. S2E mode is for symbolic execution (i386-s2e-softmmu).
- The s2eget tutorial is missing BaseInstructions in the config file, thanks for noticing.

**Comment by Qining** [comment]
Thanks! This is much clearer.
